name: Get Android APK

on: [push, pull_request]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2

      - name: setup java sdk
        uses: actions/setup-java@v1
        with:
          java-version: '9.0.4'
          
      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.15

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install Ionic cli
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install
        
      - name: a
        run:  npm install @capacitor/android

      - name: build the app
        run: npm run build
    
      - name: remove existing folder if there 
        run: rm -rf /home/runner/work/Bookie/Bookie/android
        
      - name: Add to android
        run: npx cap add android
  
      - name: sync with source
        run: npx cap sync

      - name: Generate the Android App Apk
        working-directory: /home/runner/work/Bookie/Bookie/android
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload dev APK
        uses: actions/upload-artifact@v1
        with:
          name: app-dev
          path: android/app/build/outputs/apk/debug/app-debug.apk
